quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.transaction-manager.default-transaction-timeout=300

# MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/wtovr
quarkus.datasource.username=prueba
quarkus.datasource.password=prueba
quarkus.datasource.db-version=5.5.5

# Hibernate/JPA
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=false