quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.transaction-manager.default-transaction-timeout=300

# MariaDB
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3306/wtovr
quarkus.datasource.username=prueba
quarkus.datasource.password=prueba

# Hibernate/JPA
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=false